sudo: required

language: go

services:
  - docker

env:
  - GO111MODULE=on
  
script:
   - go test -v -coverprofile=coverage.out ./...

after_success:
  - bash <(curl -s https://codecov.io/bash) -P ${CODECOV_TOKEN##*/}